{
    'name': 'Theme Corby',
    'category': 'Theme/eCommerce',
    'summary': 'Theme Corby is Odoo Multipurpose Theme '
               'with Modern style, Extremely customizable, Clean and Fully Responsive.',
    'description': 'Theme Corby is Odoo Multipurpose Theme '
                   'with Modern style, Extremely customizable, Clean and Fully Responsive.',
    'version': '12.0.1.0.0',
    'author': 'Tecspek',
    'data': [
        'views/assets.xml',
        'views/mid_header.xml',
        'views/product_carousel.xml',
        'views/customize_assets.xml',
        'views/customize_template.xml',
        'snippets/s_filter_advance.xml',
        'views/shop_template.xml',
        'views/cart_template.xml',
        'views/product_public_category_view.xml',
        'views/single_product_template.xml',
        'views/contact_us.xml',
        'views/about_us.xml',
        'views/blogs_carousel.xml',
        #'views/collapse_categories_template.xml',
        'data/homepage.xml',
        'data/footer.xml',

        'snippets/s_5_product_carousel.xml',
        'snippets/s_2_product_carousel.xml',
        'snippets/s_banner_with_category.xml',
        'snippets/s_blog_carousel.xml',
        'snippets/s_our_team.xml',
        'snippets/s_services.xml',
        'snippets/s_side_single_img.xml',
        'snippets/s_single_img.xml',
        'snippets/s_tab_carousel.xml',
        'snippets/s_testimonial.xml',
        'snippets/s_theme_banner.xml',
        'snippets/s_three_imgs.xml',
        'snippets/s_blank_block.xml',
        'snippets/s_full_homepage.xml',
        'snippets/s_category_with_image.xml',
    ],
    'depends': [
        'mass_mailing',
        'website_blog',
        'website_crm',
        'website_sale',
        'website_sale_wishlist',
        'website_sale_comparison',
        'website_sale_stock',
        # ================================================================ #
        # TecSpek Extra Addons
        # ================================================================ #

        'website_product_quick_view',
        'website_product_carousel',
        'website_product_brand',
        'tecspek_all_options',
        'tecspek_website_megamenu',
        'website_product_advance_filters',
    ],
    'demo': [
        'data/brand_demo.xml',
        'data/blog_post_demo.xml',
        'data/menu.xml',
    ],
    'images': [
        'static/description/main.png',
        'static/description/full_screenshot.png',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 175,
    'currency': 'EUR',
}
